### ISSUE TITLE
Reconfig/HUP doesn't seem to add new consoles

### ISSUE THREAD

**Issue by seitzbg** [dun/conman#26] opened 2017-03-09 21:56 UTC
I don't know if this is a bug, but when I HUP the daemon it logs a reconfig event, but doesn't recognize the new consoles I added to conman.conf until restart :(

**Comment by dun** [comment] 2017-03-09 22:25
This is a duplicate of #13.  There's some discussion there as to why this is the current behavior and what would be involved in adding this functionality.  Looks like this is currently the most requested feature.

The code was originally written assuming the configuration was static.  It simplified development and addressed our immediate need at the time since the configuration could be changed with a quick restart of the daemon.  Our clusters were much smaller back then.

Sorry for the :(.  I haven't found time to work on this yet.

**Closed by dun** 2017-03-09 22:25 UTC
Labels: duplicate

**Comment by seitzbg** [comment] 2017-03-09 22:38
No worries, thanks for the reply!

On Thu, Mar 09, 2017 at 02:25:28PM -0800, Chris Dunlap wrote:
> This is a duplicate of #13. There's some discussion there as to why this is the
> current behavior and what would be involved in adding this functionality. Looks
> like this is currently the most requested feature.
> 
> The code was originally written assuming the configuration was static. It
> simplified development and addressed our immediate need at the time since the
> configuration could be changed with a quick restart of the daemon. Our clusters
> were much smaller back then.
> 
> Sorry for the :(. I haven't found time to work on this yet.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.*
> 

-- 
             
Bryan G. Seitz
